name: single_bloc_base
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://www.github.com/modulovalue/single_bloc_base.dart
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>

environment:
  sdk: '>=2.4.4 <3.0.0'

dev_dependencies:
  extra_pedantic: ^1.1.1
  test: ^1.6.0
